use_frameworks!

platform :ios, '8.0'

target 'CommonSDImage_Example' do
  pod 'CommonSDImage', :path => '../'

  target 'CommonSDImage_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
